feat: Update kavita integration to update specific libraries, when specified
oae/kaizoku pull request #96
Opened 2023-05-02 00:35 UTC by ShivamAmin

# Pull Request Template

## Description

Add setting to Kavita integration to specify targeted libraries.
Update prisma migration to add new config setting (Not familiar with prisma, not sure if this was done correctly)
Update kavita library scan code to filter out libraries not matching new setting.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] My commits follow the commit standards of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

2023-05-02 00:37 UTC, ShivamAmin commented
The new setting is of type string. If you want to scan all libraries, leave it blank. If you want it to scan one or more libraries, specify the library names like: `Manga, Books` which will scan your 'Manga' and 'Books' libraries when a notification is sent

2023-05-02 08:54 UTC, oae requested changes

2023-05-02 08:54 UTC, oae commented on prisma/migrations/20221124200902_add_kavita/migration.sql
> +ADD COLUMN     "kavitaLibraries" TEXT;
Can you create new migration? This will break the update if they are already on this version.

2023-05-02 08:54 UTC, oae commented on prisma/schema.prisma
> +  kavitaLibraries      String?
I think it is better to make this `kavitaLibraries String[] @default([])`

2023-05-02 08:54 UTC, oae commented on src/components/settings/integration.tsx
> +            <TextItem
I think `<ArrayItem />` is better suited here.

2023-05-02 08:55 UTC, oae commented
Hi, Thank you for the pr. I have left a couple of feedbacks. Can you check them?

2023-05-06 15:35 UTC, oae approved these changes

2023-05-06 15:35 UTC, merged